### ISSUE TITLE
Dependencies / Requirements not included

### ISSUE THREAD

**Issue by b-morgan** [arhi/gcodestat#1]
Running gcodestat.exe on Windows 10 generates the following error:

The code execution cannot proceed because libgcc_s_dw2-1.dll was not found. Reinstalling the program may fix this problem.

This project should list the environments / operating systems supported and what additional tools / libraries need to be installed for it to run.

**Comment by arhi** [comment]
Thanks for reporting this! 
The dependency walker didn't show anything and I have gcc environment installed everywhere so I didn't notice it requires additional libraries. Apologies for that!
I'll change Makefile to build this one in statically and add a new release statically built asap. (missing file is part of gcc build tools for windows).

**Comment by arhi** [comment]
pushed changes that solve this ( https://github.com/arhi/gcodestat/commit/6b34f38dd3d7dbc912720bd84e94e4d6f9e04655 )

released v0.6 that is statically linked (win32), tested on blank win10 so it should be ok now
https://github.com/arhi/gcodestat/releases/tag/0.6

again @b-morgan thanks for testing and reporting problem

**Comment by b-morgan** [comment]
You are welcome!
