### ISSUE TITLE
Just "Total time: ( -14:-8 )"

### ISSUE THREAD

**Issue by burn2k** [arhi/gcodestat#2]
If I try to calculate the build time with version 0.6, I get only "Total time: ( -14:-8 )" as a result with all of my gcodes. If I use the integrated test.gcode, everything works fine.

**Comment by arhi** [comment]
can you upload one of the g-codes that fail (return ( -14:-8 )) so that I can see where the bug is?
what generated those g-codes?
thanks

**Comment by burn2k** [comment]
Sure, here is an example, generated with Simplify3d 4.01:


[string_test_fast_pyramid_8mm.zip](https://github.com/arhi/gcodestat/files/1745247/string_test_fast_pyramid_8mm.zip)

**Comment by arhi** [comment]
thanks for the sample, I see this is S3D generated should be easy... anyhow I reproduced the bug so ..

**Comment by arhi** [comment]
@burn2k for start there's a bug in your G-Code, looks like S3D has a bug .. they replace , with \n and you have in startup script
```
G1 Z0.1 ; Nozzle senken um 0,1
``` 
and this 0,1 they convert to 0\n1 so exported g-code (you can look in any txt editor) looks like:
```
G90
M82
M106 S255
G4 P500
M106 S0
; Temperaturen parallel vorheizen
M104 S205 T0; Extruder Temperatur setzen
M190 S65 T0 ; Bett heizen
M109 S205 T0 ; Extruder heizen
;Achsen nullen
G28 ; home all axes
; Düse vorbereiten
G1 X5.0 Y5.0 F7200 ; Fahre in Ausgangsposition
G1 Z0.1 ; Nozzle senken um 0
1
 
G1 X5.0 F7200 ; Material abstreifen
 
G1 Z0.2 ; Hebe Nozzle an auf 0
2mm
 
G1 X200 E20 F600 ;Linie ziehen
G92 E0
G1 E-8.0000 F9000
```
and those "1" alone in line and "2mm" alone in line (what they converted , to new line from your 0,1 and 0,2mm) are making G-code erroneous...

now this is not the bug that's affecting gcodestat, it will affect most printers (some will just ignore the error but you should fix that for your own sake and maybe report bug to s3d)

what is a problem here is this line
```
G1 X5.0 Y5.0 F7200 ; Fahre in Ausgangsposition
```

or to be precise the comment in that line. I have no clue why, will check in a minute but if you remove the comment there everything works ok :) (so there's a workaround, just remove that comment from your startup script, leave only g-code and it should work ok)

I'll be back with more asap

**Comment by burn2k** [comment]
Cool, thx for the fast reply. I will remove all comments and report back.

Edit: Everything works perfect now :)

**Comment by arhi** [comment]
fixed the bug :D stupid error in parsing the gcode line so I continued parsing after ; .. building new release and uploading fixes

**Comment by arhi** [comment]
@burn2k  thanks for report! and for testing.

release v0.7 is up: https://github.com/arhi/gcodestat/releases/tag/0.7

please try and lemme know if it works now as expected :D

**Comment by burn2k** [comment]
Yes, all problems are gone for me!
