### ISSUE TITLE
Import config data from S3D fff file

### ISSUE THREAD

**Issue by do-web** [arhi/gcodestat#3]
Then there is no need to file out the config.txt

**Comment by arhi** [comment]
not really as in s3d fff file there is no data about acceleration nor junction deviation nor jerk what makes the s3d time calculation wrong in the first place. 
the config.txt is from your firmware (config.txt comes from smoothieware). 
if you configure acceleration and jerk/junction trough G-code (trough startup script in s3d) then gcodestat will pick up those data from the generated g-code itself ... 

for example one of my profiles on s3d looks like this, in "scripts/starting script" I have
```
M17
G28
M200 D0
M204 S1500
```

and then in the additional terminal for postprocessing.. I have

```
{REPLACE "; outer perimeter\n" "; outer perimeter\nM204 S300\n"}
{REPLACE "; inner perimeter\n" "; inner perimeter\nM204 S800\n"}
{REPLACE "; solid layer\n" "; solid layer\nM204 S1000\n"}
{REPLACE "; infill\n" "; infill\nM204 S1500\n"}
e:\Dev\eclipse-workspace\gcodestat\gs.bat "[output_filepath]" 
```

so the gcodestat will set at the beginning the acceleration to 1500 and then update to 300, 800, 1000, 1500 troughout the code .. so no need to provide acceleration settings to gcodestat in that case at all ... the config.txt (in case you have smoothieware) or input params (-a, -d ..) are used just as "initial values", defaults if you do not change them trough g-code
