### ISSUE TITLE
Can't figure out how to fill in the config

### ISSUE THREAD

**Issue by QuickChemist** [arhi/gcodestat#4]
I know I'm being somewhat of a nuisance but could you help me?
I'm using a monoprice maker select plus. These are the eeprom settings.
```
Send: M501
Recv: echo:V49 stored settings retrieved (634 bytes; crc 58238)
Recv: echo:  G21    ; Units in mm
Recv: 
Recv: echo:Filament settings: Disabled
Recv: echo:  M200 D1.75
Recv: echo:  M200 D0
Recv: echo:Steps per unit:
Recv: echo:  M92 X81.00 Y81.00 Z400.50 E103.60
Recv: echo:Maximum feedrates (units/s):
Recv: echo:  M203 X450.00 Y450.00 Z5.00 E25.00
Recv: echo:Maximum Acceleration (units/s2):
Recv: echo:  M201 X1000 Y1000 Z100 E1000
Recv: echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
Recv: echo:  M204 P800.00 R800.00 T800.00
Recv: echo:Advanced: S<min_feedrate> T<min_travel_feedrate> B<min_segment_time_us> X<max_xy_jerk> Z<max_z_jerk> E<max_e_jerk>
Recv: echo:  M205 S0.00 T0.00 B20000 X8.00 Y8.00 Z0.40 E1.00
Recv: echo:Home offset:
Recv: echo:  M206 X0.00 Y0.00 Z0.00
Recv: echo:PID settings:
Recv: echo:  M301 P23.03 I1.38 D95.78
```

**Comment by arhi** [comment]
sorry for late reply somehow the email notification about this one got missed by me :( ... 
not a nuisance, no worries :)

The config.ini is a config file from smoothieware, that is a 32bit firmware that you don't need to recompile when you change stuff, you just change the config file and everything is in there, from pin definitions to acceleration and other stuff.. you are using marlin so you should not use config but put required parameters to gcodestat executable.. 

so your max feedrate is:
> Recv: echo:Maximum feedrates (units/s):
> Recv: echo:  M203 X450.00 Y450.00 Z5.00 E25.00

and default acceleration is:
> Recv: echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
> Recv: echo:  M204 P800.00 R800.00 T800.00

so your gs.bat could be:

```
@echo off

for %%a in (%1) do (
    set filepath=%%~dpa
    set filename=%%~na
    set extension=%%~xa
)
set if=%filepath%%filename%%extension%
set of=%filepath%%filename%_M117%extension%

E:\path\to\gcodestat.exe -a 800 -f 450 -s 10 --alert --gcode="%if%" --output="%of%" --api_key=XXXXXXXX --api_url="http://octopi.local/api/files/local"

```
this will use 800 as default acceleration, 450 as max feedrate will generate file with _M117 in the name where a M117 codes will be embedded every 10% of the time to finish and will send the file to local octopi with api key XXXXXXXX ... so replace the api-key value and uyrl to your octopi and voila.. 

if you don't use octoprint and don't want M117 to be generated .. so just to parse the file and report the time to finish something like this in your gs.bat:


```
@echo off

for %%a in (%1) do (
    set filepath=%%~dpa
    set filename=%%~na
    set extension=%%~xa
)
set if=%filepath%%filename%%extension%
set of=%filepath%%filename%_M117%extension%

E:\path\to\gcodestat.exe -a 800 -f 450 --alert --gcode="%if%" 

```

hope this helps

**Comment by arhi** [comment]
closing the question for now, if anything unclear feel free to reopen
