### ISSUE TITLE
Compile on RPi

### ISSUE THREAD

**Issue by eyal0** [arhi/gcodestat#8]
I had to make changes to get it to compile on RPi.  I stripped out all the curl code.  Maybe you would consider removing that and putting it into a different binary?  Because the analysis of the code and the uploading are two separate abilities that could be run one after the other.

Anyway, if you're curious, the time to run on a pretty big file on my fast desktop was 0.22seconds and on RPi was 2.7seconds.  So not too bad!  This is a really big file so it's completely reasonable this analysis would happen on RPi.

**Comment by arhi** [comment]
I have a version with #defines for compilation with/without curl (for compilation on rpi), but looks like I did not push the changes to git, will do it over the weekend (I was sure that version was pushed ages ago)
